CREATE TABLE IF NOT EXISTS cidades (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    estado_id INT UNSIGNED NOT NULL REFERENCES estados(id),
    area DECIMAL(10,2)
)